"""Shared Susan protocol helpers for CLI, MCP, and project sync."""

from __future__ import annotations

from datetime import UTC, datetime
import json
from pathlib import Path
import re
import shutil
import subprocess
from typing import Any

from anthropic import Anthropic
from supabase import create_client
import yaml

from rag_engine.retriever import Retriever
from susan_core.config import config

from .catalog import ControlPlaneCatalog
from .foundry import build_company_blueprint, mode_options_for_task, suggest_mode


SOURCE_COMMANDS = [
    "susan-query.md",
    "susan-fast.md",
    "susan-think.md",
    "susan-design.md",
    "susan-foundry.md",
    "susan-plan.md",
    "susan-status.md",
    "susan-team.md",
    "susan-assets.md",
    "susan-refresh.md",
    "susan-route.md",
    "susan-bootstrap.md",
]

PROJECT_MCP_SERVER_ID = "susan-intelligence"
PROJECT_MCP_SERVER = {
    "command": str(config.base_dir / ".venv" / "bin" / "python3"),
    "args": ["-m", "mcp_server.server"],
    "cwd": str(config.base_dir),
}
PROJECT_PRE_TOOL_HOOK = {
    "matcher": "Edit|Write",
    "command": (
        "if echo \"$CLAUDE_FILE_PATH\" | grep -q 'susan-outputs/'; "
        "then echo 'BLOCK: susan-outputs/ is generated by Susan. Use /susan-plan to regenerate.' >&2; "
        "exit 2; fi; exit 0"
    ),
}

ROUTE_KEYWORDS = {
    "design-studio-director": ["design system", "design principles", "critique", "experience system", "studio", "guidelines", "moments of truth", "jtbd", "jobs to be done", "5 whys", "five whys", "cognitive studio", "case library", "design memory", "anti-pattern", "antipattern", "critique rubric", "ux scraper", "gold standard", "double black box"],
    "landing-page-studio": ["landing page", "hero", "homepage", "scroll", "conversion page", "narrative page", "emotional arc", "proof architecture", "first days", "landing page case", "homepage anti-pattern"],
    "app-experience-studio": ["onboarding", "app flow", "core loop", "retention", "return experience", "product flow", "moments of truth", "first-use", "activation", "ux scraper", "gold standard"],
    "ai-product-manager": ["ai product", "ai pm", "rollout", "non-deterministic", "nondeterministic", "evaluation gate", "confidence band", "agentic product", "sequencing"],
    "marketing-studio-director": ["marketing studio", "messaging architecture", "asset system", "campaign system", "content system", "research spine", "belief shift", "cognitive studio", "template cascade", "case library", "marketing anti-pattern", "message anti-pattern"],
    "social-media-studio": ["social media", "instagram", "tiktok", "reels", "short-form", "short form", "social studio", "distribution"],
    "coaching-architecture-studio": ["coach architecture", "coach voice", "coaching", "conversation", "text message", "text-messaging", "motivational coach", "coach system", "love map", "love maps", "therapeutic alliance", "perceived responsiveness", "relational endowment", "personal knowledge map", "coach relationship"],
    "conversation-designer": ["conversation designer", "coach persona", "dialogue", "motivational interviewing", "coach tone", "message taxonomy", "silence rules", "therapeutic alliance"],
    "workout-session-studio": ["workout logging", "active session", "workout screen", "session ux", "set logging", "rest timer", "gym session", "conversation ui", "coach thread", "session spine", "coach cue", "intervention cue", "moment of truth cue"],
    "algorithm-lab": ["algorithm", "scoring", "adaptation logic", "fatigue model", "readiness", "recommendation engine", "math model", "monte carlo", "simulation", "predictive analytics", "risk model", "intervention window"],
    "knowledge-engineer": ["knowledge engineer", "ontology", "taxonomy", "rag", "retrieval", "memory schema", "provenance", "knowledge graph"],
    "ai-evaluation-specialist": ["ai eval", "evaluation specialist", "trace review", "regression set", "quality gate", "conversation eval", "rubric"],
    "workout-program-studio": ["workout program", "programming", "mesocycle", "microcycle", "split", "hypertrophy plan", "strength plan", "progression", "periodization", "exercise selection", "substitution logic", "re-entry", "full body", "upper lower", "push pull legs", "ppl", "dumbbell program", "home workout plan", "12-week program", "fitness guru", "influencer recommendation", "creator recommendation"],
    "training-research-studio": ["training research", "exercise science review", "systematic review", "evidence review", "literature review", "exercise library", "exercise catalog", "movement library", "ai workout plan", "competitor reviews", "program evidence", "rest intervals", "training to failure", "weekly volume", "frequency", "split comparison", "pubmed", "fitness influencer", "youtube recommendations", "academic frontier"],
    "research-director": ["research", "evidence", "benchmark", "competitor", "compare", "market", "source", "investigate"],
    "research-ops": ["refresh", "crawl", "ingest", "dataset", "coverage", "freshness", "contradiction", "pipeline"],
    "deck-studio": ["deck", "slides", "presentation", "pitch", "storyboard", "narrative", "keynote"],
    "whitepaper-studio": ["white paper", "whitepaper", "report", "pillar", "thought leadership"],
    "memo-studio": ["memo", "brief", "decision memo", "internal note"],
    "article-studio": ["article", "blog", "post", "essay", "newsletter"],
    "recruiting-strategy-studio": ["recruiting", "recruiting strategy", "school fit", "offer strategy", "visit strategy"],
    "highlight-reel-studio": ["highlight reel", "film", "hudl", "video", "clips", "recruiting film"],
    "coach-outreach-studio": ["coach outreach", "dm", "email", "coaches", "contact coaches", "outreach sequence"],
    "x-growth-studio": ["x ", "twitter", "twitter strategy", "twitter growth", "coach visibility", "sports social"],
    "recruiting-dashboard-studio": ["recruiting dashboard", "pipeline dashboard", "coach crm", "recruiting analytics", "board"],
    "oracle-health-marketing-lead": ["oracle health", "messaging", "positioning", "campaign", "gtm", "launch", "persona"],
    "oracle-health-product-marketing": ["oracle health", "buyer", "persona", "battlecard", "value prop", "product marketing"],
    "marcus": ["ux", "ui", "landing page", "website", "web design", "motion", "design system", "layout"],
    "mira": ["emotion", "delight", "experience", "tone", "feeling"],
    "prism": ["brand", "identity", "voice", "narrative"],
    "lens": ["accessibility", "wcag", "inclusive"],
    "echo": ["neuro", "attention", "cognitive", "decision friction"],
    "compass": ["product", "roadmap", "spec", "feature", "requirements", "stage gate", "decision log", "operating cadence"],
    "atlas": ["architecture", "backend", "platform", "system", "integration", "api", "performance", "company genome", "evidence graph", "event taxonomy", "telemetry"],
    "nova": ["ai", "rag", "agent", "llm", "automation", "ml"],
    "forge": ["qa", "test", "regression", "eval", "quality"],
    "pulse": ["data", "analytics", "metric", "model", "forecast"],
    "sentinel": ["security", "auth", "permission", "threat", "vulnerability"],
    "steve": ["strategy", "market", "pricing", "positioning", "why now", "wedge"],
    "aria": ["growth", "activation", "acquisition", "retention", "funnel", "loop"],
    "beacon": ["aso", "app store", "keyword ranking", "listing"],
    "haven": ["community", "creator", "forum"],
    "guide": ["customer success", "onboarding", "education", "adoption"],
    "herald": ["pr", "press", "announcement", "narrative"],
    "bridge": ["partnership", "ecosystem", "channel"],
    "vault": ["fundraising", "investor", "raise"],
    "ledger": ["finance", "budget", "unit economics", "modeling"],
    "freya": ["behavior", "motivation", "incentive", "retention", "psychology", "love map", "love maps", "relational endowment", "perceived responsiveness", "behavioral science"],
    "quest": ["gamification", "challenge", "streak", "progression"],
    "flow": ["sports psychology", "mindset", "motivation", "adherence", "therapeutic alliance", "relatedness", "relational depth"],
    "coach": ["exercise", "training", "programming", "fitness", "muscle", "hypertrophy", "strength", "squat", "bench", "deadlift", "exercise selection", "split"],
    "sage": ["nutrition", "diet", "protein", "macro", "glp-1"],
    "drift": ["sleep", "recovery", "readiness", "hrv"],
    "shield": ["legal", "compliance", "hipaa", "claim", "regulatory"],
}

DATA_TYPE_KEYWORDS = {
    "studio_open_research": ["liquid glass", "view transitions", "webkit", "scroll-driven", "scrolltrigger", "flip", "jobs to be done", "jtbd", "journey map", "zero moment of truth", "double diamond", "motion narrative"],
    "visual_asset": ["deck", "slides", "presentation", "screenshot", "visual", "brand", "storyboard", "homepage"],
    "content_strategy": ["messaging", "positioning", "white paper", "whitepaper", "memo", "article", "blog", "deck", "slides", "narrative"],
    "market_research": ["market", "competitor", "landscape", "benchmark", "buyer", "segment", "pricing", "gtm", "staffing benchmark"],
    "technical_docs": ["architecture", "api", "integration", "workflow", "technical", "ehr", "interoperability"],
    "legal_compliance": ["hipaa", "legal", "regulatory", "compliance", "policy", "claim", "cms", "uscdi"],
    "ux_research": ["ux", "ui", "landing", "design", "interaction", "onboarding", "conversion"],
    "emotional_design": ["emotion", "emotional", "feeling", "moments of truth", "5 whys", "five whys", "jtbd", "jobs to be done", "trust", "known-ness", "coach voice"],
    "behavioral_economics": ["behavioral science", "behavioral economics", "love map", "love maps", "relational endowment", "perceived responsiveness", "therapeutic alliance", "relatedness", "uncanny valley", "staleness decay", "adherence", "behavior change"],
    "growth_marketing": ["growth", "activation", "retention", "acquisition", "campaign"],
    "studio_case_library": ["case library", "case study", "precedent", "examples", "example bank", "reference set", "teardown"],
    "studio_antipatterns": ["anti-pattern", "antipattern", "what not to do", "avoid", "failure mode", "generic trap"],
    "studio_memory": ["memory", "lessons learned", "what worked", "what failed", "postmortem", "memory seed"],
    "studio_templates": ["template", "template library", "template cascade", "brief template", "skeleton", "blueprint"],
    "studio_evals": ["eval", "evaluation", "rubric", "scorecard", "critique rubric", "review rubric"],
    "training_research": ["workout program", "training research", "mesocycle", "microcycle", "hypertrophy", "strength plan", "periodization", "autoregulation", "exercise science"],
    "program_library": ["full body", "upper lower", "push pull legs", "ppl", "dumbbell program", "home workout plan", "busy lifter", "program library", "12-week program", "mesocycle", "split recommendation", "full body foundations", "ulph", "scientific ppl", "efficient hypertrophy", "dumbbell momentum"],
    "guru_research": ["fitness guru", "influencer", "youtube", "jeff nippard", "dr mike", "renaissance periodization", "greg nuckols", "stronger by science", "layne norton", "biolayne", "menno henselmans", "andy galpin", "house of hypertrophy"],
    "frontier_academic_research": ["pubmed", "latest paper", "latest papers", "frontier research", "academic research", "top colleges", "top universities", "sports medicine paper", "motivation paper", "2025 review", "2026 research"],
    "consumer_failure_patterns": ["dropout", "failure pattern", "fell off", "missed session", "adherence risk", "plateau", "consumer failure", "where users fail", "friction pattern"],
    "predictive_coaching": ["coach cue", "coach cues", "intervention", "what to say", "predictive coaching", "moment of truth cue", "re-entry cue", "first missed session"],
    "simulation_models": ["monte carlo", "simulation", "predictive analytics", "risk window", "intervention window", "risk model"],
    "exercise_catalog": ["exercise library", "exercise catalog", "movement library", "exercise database", "exercise examples", "exercise selection", "substitution"],
    "exercise_science": ["exercise", "training", "fitness", "programming"],
    "coaching_architecture": ["coach architecture", "coach voice", "coach messaging", "coach cognition", "conversation ui", "coaching loop", "personal knowledge map", "relationship memory", "warm handoff"],
    "session_ux": ["workout logging", "active session", "set logging", "session ux", "rest timer", "exercise card", "gym flow"],
    "algorithm_design": ["algorithm", "readiness", "adaptation", "scoring", "fatigue model", "recommendation model"],
    "social_growth": ["social", "twitter", "x ", "instagram", "tiktok", "reels", "creator", "distribution"],
    "recruiting_intelligence": ["recruiting", "coach fit", "school fit", "offer", "visit", "eligibility"],
    "recruiting_film": ["film", "highlight reel", "hudl", "clips", "video"],
    "coach_outreach": ["coach outreach", "coaches", "dm", "email", "contact"],
    "dashboard_design": ["dashboard", "board", "crm", "pipeline", "analytics"],
    "nutrition": ["nutrition", "macro", "protein", "diet"],
    "sleep_recovery": ["sleep", "recovery", "hrv", "readiness"],
    "sports_psychology": ["mindset", "motivation", "identity", "adherence"],
    "user_research": ["reviews", "reddit", "complaints", "voice of customer", "customer language", "friction"],
    "security": ["security", "auth", "permission", "threat"],
    "finance": ["finance", "budget", "revenue", "economics"],
    "partnerships": ["partnership", "ecosystem", "channel"],
    "operational_protocols": ["protocol", "playbook", "runbook", "cadence", "stage gate", "workflow", "operating model", "operating system", "sop", "foundry kernel", "domain factory"],
    "expert_knowledge": ["persona", "role atlas", "expert", "mental model", "specialist", "operator", "expert council", "staffing", "hiring", "team architecture", "scorecard"],
}

COMPANY_CORE_AGENTS = {
    "shared": ["susan", "research-director", "steve", "compass", "atlas"],
    "transformfit": [
        "susan",
        "design-studio-director",
        "marketing-studio-director",
        "ai-product-manager",
        "conversation-designer",
        "coach",
        "workout-program-studio",
        "training-research-studio",
        "coaching-architecture-studio",
        "workout-session-studio",
        "social-media-studio",
        "knowledge-engineer",
        "ai-evaluation-specialist",
        "algorithm-lab",
    ],
    "alex-recruiting": [
        "susan",
        "recruiting-strategy-studio",
        "highlight-reel-studio",
        "coach-outreach-studio",
        "x-growth-studio",
        "recruiting-dashboard-studio",
    ],
    "oracle-health-ai-enablement": [
        "susan",
        "research-director",
        "research-ops",
        "design-studio-director",
        "marketing-studio-director",
        "oracle-health-marketing-lead",
        "oracle-health-product-marketing",
        "deck-studio",
        "whitepaper-studio",
        "shield",
        "atlas",
        "steve",
    ],
    "founder-intelligence-os": [
        "susan",
        "research-director",
        "research-ops",
        "compass",
        "atlas",
        "steve",
        "design-studio-director",
        "marketing-studio-director",
        "shield",
        "pulse",
    ],
}

TRANSFORMFIT_EXPERIENCE_BENCH = {
    "design-studio-director": 6,
    "app-experience-studio": 8,
    "workout-session-studio": 6,
    "coaching-architecture-studio": 6,
    "conversation-designer": 7,
    "ai-product-manager": 5,
    "marcus": 4,
    "mira": 4,
    "lens": 4,
    "echo": 4,
}


def _registry() -> dict[str, Any]:
    return yaml.safe_load((config.data_dir / "agent_registry.yaml").read_text(encoding="utf-8")) or {}


def _companies() -> dict[str, Any]:
    data = yaml.safe_load((config.data_dir / "company_registry.yaml").read_text(encoding="utf-8")) or {}
    return data.get("companies", {})


def _company_defaults(company_id: str) -> list[str]:
    return COMPANY_CORE_AGENTS.get(company_id, COMPANY_CORE_AGENTS["shared"])


def _keyword_in_text(text: str, keyword: str) -> bool:
    normalized = keyword.strip().lower()
    if not normalized:
        return False

    prefix = r"\b" if normalized[0].isalnum() else ""
    suffix = r"\b" if normalized[-1].isalnum() else ""
    pattern = f"{prefix}{re.escape(normalized)}{suffix}"
    return re.search(pattern, text) is not None


def _keyword_hits(text: str, keywords: list[str]) -> list[str]:
    return [keyword for keyword in keywords if _keyword_in_text(text, keyword)]


def _contains_any(text: str, keywords: list[str]) -> bool:
    return any(_keyword_in_text(text, keyword) for keyword in keywords)


def _route_candidates(task: str, company_id: str, agent_registry: dict[str, Any]) -> list[dict[str, Any]]:
    task_lower = task.lower()
    agents = agent_registry.get("agents", {})
    scores: dict[str, int] = {}
    reasons: dict[str, list[str]] = {}

    def add(agent_id: str, score: int, reason: str) -> None:
        if agent_id not in agents:
            return
        scores[agent_id] = scores.get(agent_id, 0) + score
        reasons.setdefault(agent_id, []).append(reason)

    broad_keywords = ["plan", "build", "launch", "roadmap", "company", "go-to-market", "go to market", "strategy", "architect"]
    if _contains_any(task_lower, broad_keywords) or len(task.split()) >= 10:
        add("susan", 4, "Broad cross-functional request benefits from Susan orchestration.")
    else:
        add("susan", 1, "Susan should remain in the loop as the company architect.")

    for agent_id in _company_defaults(company_id):
        add(agent_id, 2, f"Core operator for {company_id}.")

    if company_id == "transformfit" and _contains_any(
        task_lower,
        [
            "ux",
            "ui",
            "design",
            "screen",
            "workout",
            "session",
            "logging",
            "onboarding",
            "coach",
            "coaching",
            "flow",
        ],
    ):
        for agent_id, boost in TRANSFORMFIT_EXPERIENCE_BENCH.items():
            add(agent_id, boost, "TransformFit experience request should pull the fuller design/session/coaching bench.")

    if company_id == "transformfit" and _contains_any(
        task_lower,
        [
            "love map",
            "love maps",
            "therapeutic alliance",
            "perceived responsiveness",
            "personal knowledge map",
            "relational endowment",
        ],
    ):
        add("freya", 5, "Relational coaching requests need behavioral science depth.")
        add("flow", 5, "Relational coaching requests need sports psychology depth.")

    for agent_id, keywords in ROUTE_KEYWORDS.items():
        hits = _keyword_hits(task_lower, keywords)
        if hits:
            add(agent_id, 3 + len(hits), f"Matched task language: {', '.join(hits[:3])}.")

    for agent_id, payload in agents.items():
        role_tokens = {
            token.strip(" ,/()-").lower()
            for token in f"{payload.get('role', '')} {payload.get('group', '')}".split()
            if len(token.strip(" ,/()-")) > 3
        }
        matched = sorted(token for token in role_tokens if token and _keyword_in_text(task_lower, token))
        if matched:
            add(agent_id, 1, f"Role overlap: {', '.join(matched[:3])}.")

    ranked = sorted(
        (
            {
                "agent_id": agent_id,
                "score": score,
                "reasons": reasons.get(agent_id, []),
                "group": agents[agent_id].get("group", ""),
                "rag_data_types": agents[agent_id].get("rag_data_types", []),
            }
            for agent_id, score in scores.items()
            if score > 0
        ),
        key=lambda item: (-item["score"], item["agent_id"]),
    )
    return ranked


def _route_data_types(task: str, ranked_agents: list[dict[str, Any]], evidence_hits: list[dict[str, Any]]) -> list[str]:
    task_lower = task.lower()
    recommended: list[str] = []
    seen: set[str] = set()

    for data_type, keywords in DATA_TYPE_KEYWORDS.items():
        if _contains_any(task_lower, keywords):
            recommended.append(data_type)
            seen.add(data_type)

    for candidate in ranked_agents:
        for data_type in candidate.get("rag_data_types", []):
            if data_type and data_type not in seen:
                recommended.append(data_type)
                seen.add(data_type)

    for hit in evidence_hits:
        data_type = hit.get("data_type")
        if data_type and data_type not in seen:
            recommended.append(data_type)
            seen.add(data_type)

    return recommended[:8]


def search_company_knowledge(
    query: str,
    company_id: str = "shared",
    data_types: list[str] | None = None,
    top_k: int = 8,
) -> list[dict[str, Any]]:
    retriever = Retriever()
    supabase = create_client(config.supabase_url, config.supabase_key)
    results = retriever.search(query, company_id=company_id, data_types=data_types, top_k=top_k)
    if company_id != "shared":
        shared_results = retriever.search(query, company_id="shared", data_types=data_types, top_k=top_k)
        seen_ids = {hit.get("id") for hit in results}
        for hit in shared_results:
            if hit.get("id") not in seen_ids:
                results.append(hit)
        results = sorted(results, key=lambda item: item.get("similarity", 0.0), reverse=True)[:top_k]
    row_lookup: dict[str, dict[str, Any]] = {}
    ids = [hit.get("id") for hit in results if hit.get("id")]
    if ids:
        rows = (
            supabase.table("knowledge_chunks")
            .select("id,source,source_url,metadata")
            .in_("id", ids)
            .execute()
        )
        row_lookup = {row["id"]: row for row in (rows.data or [])}
    formatted: list[dict[str, Any]] = []
    for hit in results:
        row = row_lookup.get(hit.get("id"), {})
        metadata = (row.get("metadata") or hit.get("metadata") or {})
        formatted.append(
            {
                "similarity": round(hit.get("similarity", 0.0), 4),
                "data_type": hit.get("data_type"),
                "title": metadata.get("title") or metadata.get("name") or row.get("source") or row.get("source_url") or "Untitled",
                "source": row.get("source"),
                "source_url": row.get("source_url"),
                "public_url": metadata.get("public_url"),
                "excerpt": (hit.get("content") or "")[:650],
                "metadata": metadata,
            }
        )
    return formatted


def get_company_status(company_id: str) -> dict[str, Any]:
    retriever = Retriever()
    supabase = create_client(config.supabase_url, config.supabase_key)
    companies = _companies()
    output_dir = config.companies_dir / company_id / "susan-outputs"
    output_files: list[dict[str, Any]] = []
    latest_output_at: datetime | None = None

    if output_dir.exists():
        for path in sorted(output_dir.iterdir()):
            if not path.is_file():
                continue
            modified_at = datetime.fromtimestamp(path.stat().st_mtime, UTC)
            latest_output_at = max(latest_output_at, modified_at) if latest_output_at else modified_at
            output_files.append(
                {
                    "name": path.name,
                    "path": str(path),
                    "modified_at": modified_at.isoformat(),
                    "size_bytes": path.stat().st_size,
                }
            )

    visual = (
        supabase.table("knowledge_chunks")
        .select("id", count="exact")
        .eq("company_id", company_id)
        .eq("data_type", "visual_asset")
        .execute()
    )

    return {
        "company_id": company_id,
        "company": companies.get(company_id, {}),
        "chunk_count": retriever.count_chunks(company_id),
        "visual_asset_count": visual.count or 0,
        "output_dir": str(output_dir),
        "output_files": output_files,
        "latest_output_at": latest_output_at.isoformat() if latest_output_at else None,
    }


def get_visual_assets(company_id: str, limit: int = 20) -> list[dict[str, Any]]:
    catalog = ControlPlaneCatalog()
    return [asset.model_dump(mode="json") for asset in catalog.visual_assets(company_id, limit)]


def get_team_manifest(company_id: str) -> dict[str, Any]:
    path = config.companies_dir / company_id / "susan-outputs" / "team-manifest.json"
    if not path.exists():
        return {
            "company_id": company_id,
            "status": "missing",
            "message": "Run Susan planning first to generate a team manifest.",
        }
    return json.loads(path.read_text(encoding="utf-8"))


def get_company_foundry_blueprint(company_id: str) -> dict[str, Any]:
    return build_company_blueprint(company_id)


def route_company_task(company_id: str, task: str, top_k: int = 6) -> dict[str, Any]:
    companies = _companies()
    agent_registry = _registry()
    evidence_hits = search_company_knowledge(task, company_id=company_id, top_k=top_k)
    ranked = _route_candidates(task, company_id, agent_registry)
    suggested_mode = suggest_mode(task)
    mode_options = mode_options_for_task(task)
    recommended_agents = [item["agent_id"] for item in ranked[:6]]
    recommended_data_types = _route_data_types(task, ranked[:6], evidence_hits)
    need_visual_assets = "visual_asset" in recommended_data_types or _contains_any(
        task.lower(),
        DATA_TYPE_KEYWORDS["visual_asset"],
    )
    need_research_first = (
        _contains_any(task.lower(), ["research", "evidence", "benchmark", "compare", "market", "unknown"])
        or len(evidence_hits) < 3
    )
    mode_command = {
        "quick": "/susan-fast",
        "deep": "/susan-think",
        "design": "/susan-design",
        "foundry": "/susan-foundry",
    }.get(suggested_mode, "/susan-fast")
    next_commands = ["/susan-route", "/susan-query", mode_command]
    if need_visual_assets and "/susan-assets" not in next_commands:
        next_commands.append("/susan-assets")
    if recommended_agents and "/susan-team" not in next_commands:
        next_commands.append("/susan-team")
    if "susan" in recommended_agents or len(recommended_agents) > 3 or suggested_mode in {"deep", "foundry"}:
        next_commands.append("/susan-plan")
    if need_research_first or suggested_mode in {"deep", "foundry"}:
        next_commands.append("/susan-refresh")

    rationale: list[str] = []
    if company_id in companies:
        rationale.append(f"Using the {companies[company_id].get('name', company_id)} company context.")
    if evidence_hits:
        rationale.append(f"Found {len(evidence_hits)} relevant evidence hits in the Susan corpus.")
    if len(evidence_hits) < 3:
        rationale.append("Evidence coverage is thin for this exact task, so refresh or targeted research may be needed.")
    for candidate in ranked[:4]:
        if candidate["reasons"]:
            rationale.append(f"{candidate['agent_id']}: {candidate['reasons'][0]}")

    return {
        "company_id": company_id,
        "task": task,
        "suggested_mode": suggested_mode,
        "mode_options": mode_options,
        "need_research_first": need_research_first,
        "need_visual_assets": need_visual_assets,
        "recommended_agents": recommended_agents,
        "recommended_data_types": recommended_data_types,
        "next_commands": next_commands,
        "rationale": rationale,
        "evidence_hits": evidence_hits,
    }


def maybe_model_route(company_id: str, task: str) -> dict[str, Any]:
    """Prefer fast heuristic routing and optionally refine with Claude if configured."""

    routed = route_company_task(company_id, task)
    if not config.anthropic_api_key:
        return routed

    try:
        registry = _registry()
        companies = _companies()
        payload = {
            "company": companies.get(company_id, {}),
            "task": task,
            "heuristic_route": {
                key: routed[key]
                for key in [
                    "need_research_first",
                    "need_visual_assets",
                    "recommended_agents",
                    "recommended_data_types",
                    "next_commands",
                    "rationale",
                ]
            },
            "available_agents": {
                agent_id: {
                    "role": agent["role"],
                    "group": agent["group"],
                    "rag_data_types": agent.get("rag_data_types", []),
                }
                for agent_id, agent in registry.get("agents", {}).items()
            },
        }
        client = Anthropic(api_key=config.anthropic_api_key)
        response = client.messages.create(
            model=config.model_haiku,
            max_tokens=700,
            messages=[
                {
                    "role": "user",
                    "content": (
                        "Refine this Susan routing plan. Keep the same JSON keys, preserve company_id/task, "
                        "and only change values if you have a strong reason.\n\n"
                        f"{json.dumps(payload, indent=2)}"
                    ),
                }
            ],
        )
        text = response.content[0].text
        start = text.find("{")
        end = text.rfind("}") + 1
        if start >= 0 and end > start:
            refined = json.loads(text[start:end])
            refined.setdefault("company_id", company_id)
            refined.setdefault("task", task)
            refined.setdefault("evidence_hits", routed["evidence_hits"])
            return refined
    except Exception:
        return routed
    return routed


def refresh_company_data(company_id: str) -> dict[str, Any]:
    commands: list[list[str]]
    if company_id == "oracle-health-ai-enablement":
        commands = [
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/bootstrap_oracle_health_db.py"],
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/ingest_oracle_health_domain.py"],
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/ingest_oracle_health_screenshots.py"],
        ]
    elif company_id == "transformfit":
        commands = [
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/ingest_transformfit_training_domain.py"],
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/ingest_transformfit_studio_docs.py"],
            [
                str(config.base_dir / ".venv" / "bin" / "python"),
                "-m",
                "susan_core.orchestrator",
                "--company",
                company_id,
                "--mode",
                "design",
                "--refresh",
            ],
        ]
    elif company_id == "alex-recruiting":
        commands = [
            [str(config.base_dir / ".venv" / "bin" / "python"), "scripts/ingest_alex_recruiting_domain.py"],
            [
                str(config.base_dir / ".venv" / "bin" / "python"),
                "-m",
                "susan_core.orchestrator",
                "--company",
                company_id,
                "--mode",
                "foundry",
                "--refresh",
            ],
        ]
    else:
        commands = [
            [
                str(config.base_dir / ".venv" / "bin" / "python"),
                "-m",
                "susan_core.orchestrator",
                "--company",
                company_id,
                "--mode",
                "quick",
                "--refresh",
            ]
        ]

    completed: list[dict[str, Any]] = []
    for cmd in commands:
        subprocess.run(cmd, cwd=config.base_dir, check=True)
        completed.append({"command": " ".join(cmd)})
    return {"company_id": company_id, "refreshed": True, "commands": completed}


def run_susan_plan(company_id: str, mode: str = "quick", refresh: bool = False) -> dict[str, Any]:
    cmd = [
        str(config.base_dir / ".venv" / "bin" / "python"),
        "-m",
        "susan_core.orchestrator",
        "--company",
        company_id,
        "--mode",
        mode,
    ]
    if refresh:
        cmd.append("--refresh")
    subprocess.run(cmd, cwd=config.base_dir, check=True)
    return get_company_status(company_id)


def _merge_json_file(path: Path, seed: dict[str, Any]) -> dict[str, Any]:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return seed


def _write_project_readme(target_root: Path, company_id: str, project_label: str, agents: list[str]) -> None:
    content = f"""# Susan Protocol Pack

Project: {project_label}
Default company_id: {company_id}
Central backend: {config.base_dir}

## What gets installed
- `.claude/commands/susan-*.md`
- `.claude/skills/susan-protocols/SKILL.md`
- `.mcp.json` with the Susan MCP server
- `.claude/settings.json` with Susan safety hooks
- `.susan/agents/*.md`
- `.susan/PROTOCOLS.md`
- `.susan/project-context.yaml`

## Default workflow
1. `/susan-route "task"`
2. `/susan-query "task"`
3. `/susan-fast`, `/susan-think`, `/susan-design`, or `/susan-foundry`
4. `/susan-assets` if you need screenshots/examples
5. `/susan-refresh` when the corpus needs to be refreshed

These commands default to `{company_id}` inside this repo. You can still override the company explicitly if needed.

## Core agents for this project
{chr(10).join(f"- `{agent}`" for agent in agents)}
"""
    (target_root / ".susan" / "README.md").write_text(content, encoding="utf-8")


def _write_project_context(target_root: Path, company_id: str, project_label: str, agents: list[str]) -> None:
    payload = {
        "company_id": company_id,
        "project_label": project_label,
        "central_backend": str(config.base_dir),
        "mcp_server_id": PROJECT_MCP_SERVER_ID,
        "default_commands": [command.removesuffix(".md") for command in SOURCE_COMMANDS],
        "core_agents": agents,
    }
    (target_root / ".susan" / "project-context.yaml").write_text(yaml.safe_dump(payload, sort_keys=False), encoding="utf-8")


def _write_protocol_skill(target_root: Path, company_id: str, project_label: str, agents: list[str]) -> None:
    skill_dir = target_root / ".claude" / "skills" / "susan-protocols"
    skill_dir.mkdir(parents=True, exist_ok=True)
    content = f"""---
name: susan-protocols
description: Use Susan's backend, routed agents, research corpus, and studio assets when working on strategy, research, product, marketing, or company-building tasks in this repo.
---

# Susan Protocols

This project is wired to the central Susan backend at `{config.base_dir}`.

Default company_id: `{company_id}`
Project: `{project_label}`

## Use Susan by default when
- the task spans more than one domain
- you need current research, examples, or screenshots
- you need the right specialist agents pulled in
- you are producing slides, white papers, memos, articles, or execution plans

## Default protocol
1. Run `/susan-route "task"` first for new workstreams.
2. Run `/susan-query "task"` to pull research and examples.
3. Choose one mode command: `/susan-fast`, `/susan-think`, `/susan-design`, or `/susan-foundry`.
4. Run `/susan-assets` when the output is visual, narrative, or deck-heavy.
5. Run `/susan-refresh` if the evidence is stale or coverage is thin.

Inside this repo, these commands default to `{company_id}`. Override explicitly only when you want another tenant.

## Core agents
{chr(10).join(f"- `{agent}`" for agent in agents)}

## Operating rule
Use the central backend as the source of truth, but bring the specialist agents from `.susan/agents/` into the active project conversation when their domain is required.
"""
    (skill_dir / "SKILL.md").write_text(content, encoding="utf-8")


def _install_project_mcp(target_root: Path) -> None:
    path = target_root / ".mcp.json"
    payload = _merge_json_file(path, {"mcpServers": {}})
    payload.setdefault("mcpServers", {})
    payload["mcpServers"][PROJECT_MCP_SERVER_ID] = PROJECT_MCP_SERVER
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _install_project_settings(target_root: Path) -> None:
    path = target_root / ".claude" / "settings.json"
    payload = _merge_json_file(path, {"hooks": {"PreToolUse": []}})
    hooks = payload.setdefault("hooks", {})
    pre_tool = hooks.setdefault("PreToolUse", [])
    if PROJECT_PRE_TOOL_HOOK not in pre_tool:
        pre_tool.append(PROJECT_PRE_TOOL_HOOK)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _render_command_for_target(name: str, company_id: str) -> str:
    susan_root = config.base_dir.parent
    text = (susan_root / "commands" / name).read_text(encoding="utf-8")
    injected = f"SUSAN_DEFAULT_COMPANY={company_id} ./.venv/bin/python scripts/susan_cli.py"
    text = text.replace("./.venv/bin/python scripts/susan_cli.py", injected)
    hints = {
        'argument-hint: "\\"query\\" --company company_id [--types a,b] [--top-k N]"':
            'argument-hint: "\\"query\\" [--company company_id] [--types a,b] [--top-k N]"',
        'argument-hint: "company_id [--mode quick|deep|design|foundry|full] [--refresh]"':
            'argument-hint: "[company_id] [--mode quick|deep|design|foundry|full] [--refresh]"',
        'argument-hint: "company_id"':
            'argument-hint: "[company_id]"',
        'argument-hint: "company_id [--limit N]"':
            'argument-hint: "[company_id] [--limit N]"',
        'argument-hint: "company_id \\"task\\" [--top-k N]"':
            'argument-hint: "[company_id] \\"task\\" [--top-k N]"',
    }
    for current, replacement in hints.items():
        text = text.replace(current, replacement)
    return text


def sync_project_target(target: dict[str, Any]) -> dict[str, Any]:
    root = Path(target["path"])
    claude_commands = root / ".claude" / "commands"
    susan_dir = root / ".susan"
    susan_agents = susan_dir / "agents"
    susan_hooks = susan_dir / "hooks"

    claude_commands.mkdir(parents=True, exist_ok=True)
    susan_agents.mkdir(parents=True, exist_ok=True)
    susan_hooks.mkdir(parents=True, exist_ok=True)

    susan_root = config.base_dir.parent
    for name in SOURCE_COMMANDS:
        (claude_commands / name).write_text(_render_command_for_target(name, target["company_id"]), encoding="utf-8")

    for agent_file in (susan_root / "agents").glob("*.md"):
        shutil.copy2(agent_file, susan_agents / agent_file.name)

    shutil.copy2(susan_root / "hooks" / "hooks.json", susan_hooks / "hooks.json")
    shutil.copy2(susan_root / "SUSAN_PROTOCOLS.md", susan_dir / "PROTOCOLS.md")

    agents = [agent for agent in _company_defaults(target["company_id"]) if agent in _registry().get("agents", {})]
    _write_project_readme(root, target["company_id"], target["project_label"], agents)
    _write_project_context(root, target["company_id"], target["project_label"], agents)
    _write_protocol_skill(root, target["company_id"], target["project_label"], agents)
    _install_project_mcp(root)
    _install_project_settings(root)

    return {
        "status": "synced",
        "path": str(root),
        "company_id": target["company_id"],
        "commands": len(SOURCE_COMMANDS),
        "agents": len(list((susan_root / "agents").glob("*.md"))),
        "mcp_server": PROJECT_MCP_SERVER_ID,
        "skill": "susan-protocols",
    }


def sync_project_protocols(config_path: Path | None = None) -> list[dict[str, Any]]:
    targets_path = config_path or (config.data_dir / "project_protocol_targets.yaml")
    payload = yaml.safe_load(targets_path.read_text(encoding="utf-8")) or {}
    results: list[dict[str, Any]] = []
    for target in payload.get("targets", []):
        root = Path(target["path"])
        if not root.exists():
            results.append({"status": "missing", "path": str(root), "company_id": target.get("company_id")})
            continue
        results.append(sync_project_target(target))
    return results
